FROM node:14

ENV NODE_ENV=
ENV NATS_PORT=
ENV NATS_HOST=
ENV TARANTOOL_PORT=
ENV TARANTOOL_HOST=
ENV TARANTOOL_USER_NAME=
ENV TARANTOOL_USER_PASSWORD=


RUN mkdir /www && mkdir /www/app
WORKDIR /www/app
COPY package.json .
RUN npm i
COPY . .
RUN cp src/types/custom.tarantool.d.ts node_modules/@types/tarantool-driver/index.d.ts
RUN npm run build
RUN rm -R src
CMD ["npm", "start"]
