AWSTemplateFormatVersion: '2010-09-09'
Description: Basic roles and resources for services.
Parameters:
  EnvironmentName:
    Type: String
    Default: test
    Description: The environment name, used for locating outputs from the
                 prerequisite stacks
Resources:
  BackWSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  BackQueueWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  BackApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  FrontNginxRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
Outputs:
  BackWSRole:
    Value: !GetAtt 'BackWSRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackWSRole' ] ]
  BackQueueWorkerRole:
    Value: !GetAtt 'BackQueueWorkerRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackQueueWorkerRole' ] ]
  BackApiRole:
    Value: !GetAtt 'BackApiRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackApiRole' ] ]
  FrontNginxRole:
    Value: !GetAtt 'FrontNginxRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'FrontNginxRole' ] ]