AWSTemplateFormatVersion: '2010-09-09'
Description: Application services and tasks roles
Parameters:
  EnvironmentName:
    Type: String
    Default: test
    Description: The environment name, used for locating outputs from the
                 prerequisite stacks
Resources:
  BackWSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  BackQueueWorkerTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  BackApiTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  FrontNginxTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
Outputs:
  BackWSTaskRole:
    Value: !GetAtt 'BackWSTaskRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackWSTaskRole' ] ]
  BackQueueWorkerTaskRole:
    Value: !GetAtt 'BackQueueWorkerTaskRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackQueueWorkerTaskRole' ] ]
  BackApiTaskRole:
    Value: !GetAtt 'BackApiTaskRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackApiTaskRole' ] ]
  FrontNginxTaskRole:
    Value: !GetAtt 'FrontNginxTaskRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'FrontNginxTaskRole' ] ]
