AWSTemplateFormatVersion: '2010-09-09'
Description: MySQL cluster
Parameters:
  EnvironmentName:
    Type: String
    Default: test
    Description: The environment name, used for locating outputs from the
                 prerequisite stacks
  MySQLDBName:
    Type: String
    Default: 'devplizi'
    Description: MySQLDB database default name.
  MySQLDBMasterUsername:
    Type: String
    Default: 'root'
    Description: MySQLDB admin user name.
  MySQLDBMasterUserPassword:
    Type: String
    Default: 'ecugVWHKatKQd657'
    NoEcho: true
    Description: MySQLDB admin user password.
  AllocatedStorageGb:
    Type: String
    Default: '200'
  ManagedIops: 
    Type: String
    Default: 35000
  InstanceType:
    Type: String
    Default: 'db.r5.4xlarge'
Resources:

  MySQLSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: MySQL
      SubnetIds: !Split [',', {'Fn::ImportValue': !Join [':', [!Ref 'EnvironmentName', 'PrivateSubnets']] }]
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MySQL
      VpcId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  MySQLIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'MySQLSecurityGroup'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'FargateContainerSecurityGroup']]
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
      
  MySQLParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: MySQL DB Parameter Group Description
      Family: mysql
      Parameters: {
        "log_bin_trust_function_creators": "1"
      }
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  MySQL:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref AllocatedStorageGb
      StorageType: 'io1'
      Iops: !Ref 'ManagedIops'
      DBInstanceClass: !Ref 'InstanceType'
      DBParameterGroupName: !Ref MySQLParameterGroup
      Engine: mysql
      DBName: !Ref 'MySQLDBName'
      MasterUsername: !Ref 'MySQLDBMasterUsername'
      MasterUserPassword: !Ref 'MySQLDBMasterUserPassword'
      DBSubnetGroupName: !Ref 'MySQLSubnetGroup'
      #PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt 'MySQLSecurityGroup.GroupId'
      MultiAZ: true
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    
Outputs:
  MySQLDBName:
    Value: !Ref 'MySQLDBName'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBName' ] ]
  MySQLDBUserName:
    Value: !Ref 'MySQLDBMasterUsername'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBUser' ] ]
  MySQLDBUserPass:
    Value: !Ref 'MySQLDBMasterUserPassword'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBPass' ] ]
  MySQLDBHost:
    Value: !GetAtt 'MySQL.Endpoint.Address'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBHost' ] ]
  MySQLDBPort:
    Value: !GetAtt 'MySQL.Endpoint.Port'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBPort' ] ]
  MySQLSecurityGroup:
    Value: !Ref 'MySQLSecurityGroup'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLSecurityGroup' ] ]