AWSTemplateFormatVersion: '2010-09-09'
Description: Redis cluster
Parameters:
  EnvironmentName:
    Type: String
    Default: test
    Description: The environment name, used for locating outputs from the
                 prerequisite stacks
  InstanceSize:
    Type: String
    Default: cache.m5.12xlarge
  
  NumCacheNodes:
    Type: String
    Default: 1  
Resources:
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Redis
      SubnetIds: !Split [',', {'Fn::ImportValue': !Join [':', [!Ref 'EnvironmentName', 'PrivateSubnets']] }]
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis
      VpcId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  RedisIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'RedisSecurityGroup'
      IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'FargateContainerSecurityGroup']]
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
  
  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheSecurityGroupNames:
      - !Ref RedisSecurityGroup
      Port: 6379
      NumCacheNodes: !Ref NumCacheNodes
      #VpcSecurityGroupIds:
      Engine: redis
      CacheSubnetGroupName: 
      - !Ref RedisSubnetGroup
      CacheParameterGroupName: string
      AutoMinorVersionUpgrade: true
      CacheNodeType: !Ref InstanceSize
      VpcSecurityGroupIds:
      - !Ref RedisSecurityGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

Outputs:
  RedisHost:
    Value: !GetAtt 'RedisCluster.RedisEndpoint.Address'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'RedisHost' ] ]
  RedisPort:
    Value: !GetAtt 'RedisCluster.RedisEndpoint.Port'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'RedisPort' ] ]
  RedisSecurityGroup:
    Value: !Ref 'RedisSecurityGroup'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'RedisSecurityGroup' ] ]