AWSTemplateFormatVersion: '2010-09-09'
Description: MySQL cluster
Parameters:
  EnvironmentName:
    Type: String
    Default: test
    Description: The environment name, used for locating outputs from the
                 prerequisite stacks

  MySQLDBName:
    Type: String
    Default: 'devplizi'
    Description: MySQLDB database default name.
  MySQLDBMasterUsername:
    Type: String
    Default: 'root'
    Description: MySQLDB admin user name.
  MySQLDBMasterUserPassword:
    Type: String
    Default: 'ecugVWHKatKQd657'
    NoEcho: true
    Description: MySQLDB admin user password.
  MySQLProvisionedIops:
    Type: String
    Default: '1000'
    Description: Provisioned IOps count for MySQL (RDS) database.
  MySQLDatabaseType:
    Type: String
    Default: 'db.m3.medium'
    Description: EC2 instance type used for MySQL (RDS) database hosting.
Resources:
  MySQLSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: description #required
      SubnetIds: !Split [',', {'Fn::ImportValue': !Join [':', [!Ref 'EnvironmentName', 'PublicSubnets']] }]
  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "MySQL Security Group"
      VpcId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
  MySQLIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: "MySQL ingress from Fargate container"
      GroupId: !Ref 'MySQLSecurityGroup'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'FargateContainerSecurityGroup']]
  MySQLParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
        Description: MySQL DB Parameter Group Description
        Family: MySQL8.0
        Parameters: {
          "log_bin_trust_function_creators": "1"
        }
  MySQL:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '100' # TODO Adjust for highload. GB of storage
      StorageType: 'io1'
      Iops: !Ref 'MySQLProvisionedIops'
      DBInstanceClass: !Ref 'MySQLDatabaseType'
      DBParameterGroupName: !Ref 'MySQLParameterGroup'
      Engine: MySQL
      #DBSnapshotIdentifier: !Ref 'MySQLDBName'
      DBName: !Ref 'MySQLDBName'
      MasterUsername: !Ref 'MySQLDBMasterUsername'
      MasterUserPassword: !Ref 'MySQLDBMasterUserPassword'
      DBSubnetGroupName: !Ref 'MySQLSubnetGroup'
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt 'MySQLSecurityGroup.GroupId'
      MultiAZ: true
Outputs:
  MySQLDBName:
    Value: !Ref 'MySQLDBName'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBName' ] ]
  MySQLDBUserName:
    Value: !Ref 'MySQLDBMasterUsername'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBUser' ] ]
  MySQLDBUserPass:
    Value: !Ref 'MySQLDBMasterUserPassword'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBPass' ] ]
  MySQLDBHost:
    Value: !GetAtt 'MySQL.Endpoint.Address'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBHost' ] ]
  MySQLDBPort:
    Value: !GetAtt 'MySQL.Endpoint.Port'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLDBPort' ] ]
  MySQLSecurityGroup:
    Value: !Ref 'MySQLSecurityGroup'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'MySQLSecurityGroup' ] ]