AWSTemplateFormatVersion: '2010-09-09'
Description: This stack deploys Network Load balancer with all required 
             target groups and listeners related to the current priject.
Metadata:
  cfn-lint:
    config:
      ignore_checks:
      - E3012
Parameters:
  # Network configuration
  EnvironmentName:
    Type: String
    Default: test
    Description: A name for the environment that this cloudformation will be part of.
                 Used to locate other resources in the same environment.
    AllowedValues:
      - test
      - prod
    ConstraintDescription: Environment name may be only 'test' or 'prod', to prevent
                           configuration files multiplication.
  # CertificateArn:
  #   Type: String
  #   Default: arn:aws:acm:eu-central-1:884088487044:certificate/4444446f-1db7-46ee-b983-cca853830df1
  #   Description: ARN of the Amazon Certificate Manager SSL certificate to use for this app
Resources:
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: network
      Scheme: internet-facing
      LoadBalancerAttributes:
      - Key: load_balancing.cross_zone.enabled
        Value: true
      Subnets:
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetOne']]
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetTwo']]
      Tags:
        - Key: "Name"
          Value: "network-public"
  # NLBTargetGroupWSInbound:
  #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
  #   Properties:
  #     TargetType: ip
  #     Port: 7070
  #     Protocol: TCP
  #     VpcId: 
  #       Fn::ImportValue:
  #         !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
  NLBTargetGroupWSOutbound:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetType: ip
      Port: 5555
      Protocol: TCP
      VpcId: 
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
  # NLBTargetGroupWSSSL:
  #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
  #   Properties:
  #     Port: 7070
  #     Protocol: TCP
  #     VpcId: 
  #       Fn::ImportValue:
  #         !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
  # NLBListenerWSInbound:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #     DefaultActions:
  #       - TargetGroupArn: !Ref 'NLBTargetGroupWSInbound'
  #         Type: 'forward'
  #     LoadBalancerArn: !Ref 'NetworkLoadBalancer'
  #     Port: 7070
  #     Protocol: TCP
  # NLBListenerWSInboundSSL:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #     DefaultActions:
  #       - TargetGroupArn: !Ref 'NLBTargetGroupWSSSL'
  #         Type: 'forward'
  #     LoadBalancerArn: !Ref 'NetworkLoadBalancer'
  #     Port: 7070
  #     Protocol: TCP
  NLBListenerWSOutbound:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref 'NLBTargetGroupWSOutbound'
          Type: 'forward'
      LoadBalancerArn: !Ref 'NetworkLoadBalancer'
      Port: 5555
      Protocol: TCP
  # NetworkLoadBalancerListenerCert:
  #   Type: AWS::ElasticLoadBalancingV2::ListenerCertificate
  #   Properties:
  #     Certificates:
  #       - CertificateArn: !Ref CertificateArn
  #     ListenerArn: !Ref NLBListenerWSInboundSSL
Outputs:
  NLBId:
    Description: The ARN of the Network Load Balancer
    Value: !Ref NetworkLoadBalancer
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'NLBId' ] ]
  NLBAddress:
    Description: DNS Address of Network Load Balancer
    Value: !GetAtt NetworkLoadBalancer.DNSName
    Export: 
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'NLBAddress' ] ]

  # NLBTargetGroupWSInbound:
  #   Description: The ARN of the public load balancer's Listener
  #   Value: !Ref NLBTargetGroupWSInbound
  #   Export:
  #     Name: !Join [ ':', [ !Ref 'EnvironmentName', 'NLBTargetGroupWSInbound' ] ]
  NLBTargetGroupWSOutbound:
    Description: The ARN of the NLBTargetGroupWSOutbound
    Value: !Ref NLBTargetGroupWSOutbound
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'NLBTargetGroupWSOutbound' ] ]