AWSTemplateFormatVersion: '2010-09-09'
Description: Redis, and any other resources that the chat app needs.
Parameters:
  EnvironmentName:
    Type: String
    Default: prod
    Description: The environment name, used for locating outputs from the
                 prerequisite stacks
Resources:
  ##
  ## REDIS (AWS ElasticCache), Port: 6376
  ##
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Group of subnets to place Redis into
      SubnetIds:
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetOne']]
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetTwo']]
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Redis Security Group"
      VpcId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
  RedisIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      Description: Ingress from Fargate containers
      GroupId: !Ref 'RedisSecurityGroup'
      IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'FargateContainerSecurityGroup']]
  Redis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: cache.m4.large # TODO increase volume
      NumCacheNodes: 2 # TODO change to 3
      CacheSubnetGroupName: !Ref 'RedisSubnetGroup'
      VpcSecurityGroupIds:
        - !GetAtt 'RedisSecurityGroup.GroupId'
      PreferredAvailabilityZones:
        - eu-central-1a
        - eu-central-1b
       #- eu-central-1c  # TODO
  ## 
  ## RDS (MySQL) Port: 3306
  ##
  MySQLSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      SubnetIds:
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetOne']]
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetTwo']]
  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
  MySQLIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'MySQLSecurityGroup'
      IpProtocol: tcp
      FromPort: 3306
      ToPort: 3306
      SourceSecurityGroupId:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'FargateContainerSecurityGroup']]
  MySQL:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSecurityGroups:
      - !Ref 'MySQLSecurityGroup'
      AllocatedStorage: 5
      DBInstanceClass: db.m4.large
      Engine: MySQL
      MasterUsername: 'root'
      MasterUserPassword: 'ecugVWHKatKQd657'
    DeletionPolicy: Snapshot

  ##
  ## DocumentDB (Mongo) Port 27017
  ##
  MongoSubnetGroup:
    Type: "AWS::DocDB::DBSubnetGroup"
    Properties:
      SubnetIds: #required
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetOne']]
        - Fn::ImportValue:
            !Join [':', [!Ref 'EnvironmentName', 'PublicSubnetTwo']]
  MongoInstance:
    Type: "AWS::DocDB::DBInstance"
    Properties:
      DBInstanceClass: db.m4.large #required
      DBClusterIdentifier: MongoDB #required
  MongoDB:
    Type: "AWS::DocDB::DBCluster"
    Properties:
      StorageEncrypted: true
      AvailabilityZones:
        - eu-central-1a
        - eu-central-1b
       #- eu-central-1c  # TODO
      Port: 27017
      #DBClusterIdentifier: String
      DBSubnetGroupName: MongoSubnetGroup
      DeletionProtection: false
      MasterUsername: 'plizi' #required
      MasterUserPassword: 'Tksx2PPDba8Ny0lZ' #required
      VpcSecurityGroupIds:
        Fn::ImportValue:
          !Join [':', [!Ref 'EnvironmentName', 'VPCId']]
  ## 
  ## ROLES
  ## 
  BackWSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  BackQueueWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  BackApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
  FrontNginxRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "ecs-tasks.amazonaws.com"
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
        - PolicyName: database-full-access
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:*
                - docdb:*
                - elasticache:*
              Resource: "*"
Outputs:
  RedisEndpoint:
    Value: !GetAtt 'Redis.RedisEndpoint.Address'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'RedisEndpoint' ] ]
  BackWSRole:
    Value: !GetAtt 'BackWSRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackWSRole' ] ]
  BackQueueWorkerRole:
    Value: !GetAtt 'BackQueueWorkerRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackQueueWorkerRole' ] ]
  BackApiRole:
    Value: !GetAtt 'BackApiRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'BackApiRole' ] ]
  FrontNginxRole:
    Value: !GetAtt 'FrontNginxRole.Arn'
    Export:
      Name: !Join [ ':', [ !Ref 'EnvironmentName', 'FrontNginxRole' ] ]